import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('Compact Month calendar selects canonical single and range values with keyboard month navigation @cross-browser', async ({ page }) => {
  await page.goto('/components/month-calendar')
  const single = page.locator('#components-month-calendar-single-panel-preview')
  const calendar = single.locator('#settlement-month-calendar')
  const selected = calendar.getByRole('gridcell', { name: 'Friday, September 18, 2026', exact: true })
  await expect(selected).toHaveAttribute('aria-selected', 'true')
  await calendar.getByRole('gridcell', { name: 'Sunday, September 20, 2026', exact: true }).click()
  await expect(calendar.locator('input[name="settlementDate"]')).toHaveValue('2026-09-20')
  await calendar.getByRole('gridcell', { name: 'Sunday, September 20, 2026', exact: true }).press('ArrowRight')
  await expect(calendar.getByRole('gridcell', { name: 'Monday, September 21, 2026', exact: true })).toBeFocused()
  await calendar.getByRole('button', { name: 'Next month' }).click()
  await expect(calendar.getByRole('heading')).toHaveText('October 2026')

  const range = page.locator('#components-month-calendar-range-panel-preview').locator('#reporting-range-calendar')
  await expect(range.locator('input[name="reportingStart"]')).toHaveValue('2026-09-14')
  await expect(range.locator('input[name="reportingEnd"]')).toHaveValue('2026-09-18')
  await range.getByRole('gridcell', { name: 'Monday, September 21, 2026', exact: true }).click()
  await range.getByRole('gridcell', { name: 'Thursday, September 24, 2026', exact: true }).click()
  await expect(range.locator('input[name="reportingStart"]')).toHaveValue('2026-09-21')
  await expect(range.locator('input[name="reportingEnd"]')).toHaveValue('2026-09-24')

  const bounded = page.locator('#components-month-calendar-bounds-panel-preview').locator('#booking-month-calendar')
  await expect(bounded.getByRole('gridcell', { name: /^Wednesday,? 16 September 2026$/ })).toBeDisabled()
  const fifteenth = bounded.getByRole('gridcell', { name: /^Tuesday,? 15 September 2026$/ })
  const eighteenth = bounded.getByRole('gridcell', { name: /^Friday,? 18 September 2026$/ })
  await fifteenth.press('ArrowRight')
  await expect(eighteenth).toBeFocused()
  await eighteenth.press('ArrowLeft')
  await expect(fifteenth).toBeFocused()
  const minimum = bounded.getByRole('gridcell', { name: /^Thursday,? 10 September 2026$/ })
  await minimum.press('Home')
  await expect(minimum).toBeFocused()
  const maximum = bounded.getByRole('gridcell', { name: /^Friday,? 25 September 2026$/ })
  await maximum.press('End')
  await expect(maximum).toBeFocused()
  expect((await new AxeBuilder({ page }).include('#components-month-calendar-single-panel-preview').analyze()).violations).toEqual([])

  await page.setViewportSize({ width: 320, height: 1000 })
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  const lastColumn = calendar.getByRole('gridcell', { name: 'Saturday, October 3, 2026', exact: true })
  await lastColumn.focus()
  await expect(lastColumn).toBeFocused()
  const card = (await calendar.boundingBox())!
  const cell = (await lastColumn.boundingBox())!
  expect(cell.x).toBeGreaterThanOrEqual(card.x)
  expect(cell.x + cell.width).toBeLessThanOrEqual(card.x + card.width + 1)
  await lastColumn.press('Enter')
  await expect(calendar.locator('input[name="settlementDate"]')).toHaveValue('2026-10-03')
})

test('Date picker composes labelled popover selection, validation, and unavailable states @cross-browser', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/components/date-picker')
  const basic = page.locator('#components-date-picker-panel-preview')
  const trigger = basic.getByRole('button', { name: 'Invoice date', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Invoice date calendar', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('gridcell', { name: 'Monday, September 21, 2026', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(trigger).toContainText('9/21/26')
  await trigger.click()
  await dialog.getByRole('button', { name: 'Clear date' }).click()
  await expect(dialog.locator('input[name="invoiceDate"]')).toHaveValue('')
  await expect(trigger).toContainText('Choose date')
  await page.keyboard.press('Escape')

  const invalid = page.locator('#components-date-picker-validation-panel-preview')
  await expect(invalid.getByRole('button', { name: 'Closing date', exact: true })).toHaveAttribute('aria-invalid', 'true')
  await expect(page.locator('#components-date-picker-pending-panel-preview').getByRole('button', { name: 'Availability date', exact: true })).toBeDisabled()
  await expect(page.locator('#components-date-picker-disabled-panel-preview').getByRole('button', { name: 'Archived date', exact: true })).toBeDisabled()
  expect((await new AxeBuilder({ page }).include('#components-date-picker-panel-preview').analyze()).violations).toEqual([])
})

test('Compact selection supports dropdown captions and trigger-adjacent picker placement @cross-browser', async ({ page }) => {
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.goto('/components/month-calendar')
  const captionCalendar = page.locator('#components-month-calendar-caption-panel-preview').locator('#birth-month-calendar')
  const year = captionCalendar.getByRole('combobox', { name: 'Year', exact: true })
  const month = captionCalendar.getByRole('combobox', { name: 'Month', exact: true })
  await year.selectOption('1920')
  await month.selectOption('01')
  await expect(captionCalendar.getByRole('button', { name: 'Previous month', exact: true })).toBeDisabled()
  const firstMonthDay = captionCalendar.getByRole('gridcell', { name: 'Thursday, January 15, 1920', exact: true })
  await firstMonthDay.press('PageUp')
  await expect(year).toHaveValue('1920')
  await expect(month).toHaveValue('01')
  await expect(firstMonthDay).toBeFocused()
  await year.selectOption('2026')
  await month.selectOption('12')
  const finalMonthDay = captionCalendar.getByRole('gridcell', { name: 'Tuesday, December 15, 2026', exact: true })
  await finalMonthDay.press('PageDown')
  await expect(year).toHaveValue('2026')
  await expect(month).toHaveValue('12')
  await expect(finalMonthDay).toBeFocused()
  await year.selectOption('1990')
  await month.selectOption('02')
  await expect(captionCalendar.getByRole('heading', { name: 'February 1990', exact: true })).toBeAttached()
  const presentation = await captionCalendar.evaluate(element => {
    const style = getComputedStyle(element)
    return { padding: Number.parseFloat(style.paddingTop), width: element.getBoundingClientRect().width }
  })
  expect(presentation.padding).toBeGreaterThanOrEqual(12)
  expect(presentation.width).toBeLessThanOrEqual(340)

  await page.goto('/components/date-picker')
  const basic = page.locator('#components-date-picker-panel-preview')
  const trigger = basic.getByRole('button', { name: 'Invoice date', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog', { name: 'Invoice date calendar', exact: true })
  const [triggerBox, dialogBox] = await Promise.all([trigger.boundingBox(), dialog.boundingBox()])
  expect(triggerBox).not.toBeNull()
  expect(dialogBox).not.toBeNull()
  expect(Math.abs(dialogBox!.x - triggerBox!.x)).toBeLessThanOrEqual(1)
  const blockGap = Math.min(
    Math.abs(dialogBox!.y - (triggerBox!.y + triggerBox!.height)),
    Math.abs(triggerBox!.y - (dialogBox!.y + dialogBox!.height)),
  )
  expect(blockGap).toBeLessThanOrEqual(12)
  await page.keyboard.press('Escape')

  const birthDate = page.locator('#components-date-picker-caption-panel-preview')
  await birthDate.getByRole('button', { name: 'Date of birth', exact: true }).click()
  const birthDateDialog = page.getByRole('dialog', { name: 'Date of birth calendar', exact: true })
  const pickerYear = birthDateDialog.getByRole('combobox', { name: 'Year', exact: true })
  const pickerMonth = birthDateDialog.getByRole('combobox', { name: 'Month', exact: true })
  await pickerYear.selectOption('1920')
  await pickerMonth.selectOption('01')
  const firstPickerDay = birthDateDialog.getByRole('gridcell', { name: 'Thursday, January 15, 1920', exact: true })
  await firstPickerDay.press('PageUp')
  await expect(pickerYear).toHaveValue('1920')
  await expect(pickerMonth).toHaveValue('01')
  await expect(firstPickerDay).toBeFocused()
  await pickerYear.selectOption('2026')
  await pickerMonth.selectOption('12')
  const finalPickerDay = birthDateDialog.getByRole('gridcell', { name: 'Tuesday, December 15, 2026', exact: true })
  await finalPickerDay.press('PageDown')
  await expect(pickerYear).toHaveValue('2026')
  await expect(pickerMonth).toHaveValue('12')
  await expect(finalPickerDay).toBeFocused()
  await pickerYear.selectOption('1990')
  await pickerMonth.selectOption('02')
  await birthDateDialog.getByRole('gridcell', { name: 'Thursday, February 15, 1990', exact: true }).click()
  await expect(birthDate.getByRole('button', { name: 'Date of birth', exact: true })).toContainText('2/15/90')
})
