import { test, expect } from '../fixture'

for (const surface of ['application', 'specification'] as const) {
  test(`${surface} separates personal Profile and organization Settings with guarded detail drawers @cross-browser`, async ({ page }) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    const start = surface === 'application' ? '/examples/application/accounts' : '/examples/specification/accounts/view-accounts'
    await page.goto(`${start}?ledger=jordan&environment=staging${surface === 'specification' ? '&appMode=1' : ''}`)
    await page.evaluate(() => document.documentElement.dataset.profileSession = 'same-document')
    await page.getByRole('link', { name: 'Andrew Meier', exact: true }).click()
    const nav = page.locator('#template-desktop-navigation')
    await expect(nav.getByRole('link')).toHaveText(['← Ledger', 'Profile', 'Organizations'])
    await expect(page.getByRole('heading', { name: 'Profile', exact: true, level: 1 })).toBeVisible()
    await expect(page.getByRole('textbox', { name: /^Name/ })).toHaveCount(0)
    await expect(page.locator('html')).toHaveAttribute('data-profile-session', 'same-document')
    await page.getByRole('radiogroup', { name: 'Appearance', exact: true }).getByText('Dark', { exact: true }).click()
    await expect(page.locator('html')).toHaveAttribute('data-color-mode', 'dark')
    await page.getByRole('link', { name: 'Edit profile', exact: true }).click()
    const profile = page.getByRole('dialog', { name: 'Edit profile', exact: true })
    await expect(profile).toBeVisible()
    await expect(profile.getByRole('textbox', { name: /^Name/ })).toBeFocused()
    await profile.getByRole('textbox', { name: /^Name/ }).fill('Private person <draft>')
    page.once('dialog', dialog => dialog.dismiss())
    await page.keyboard.press('Escape')
    await expect(profile).toBeVisible()
    const response = page.waitForResponse(response => response.request().method() === 'POST')
    await profile.getByRole('textbox', { name: /^Email/ }).fill('not-an-email')
    await profile.getByRole('form').evaluate((form: HTMLFormElement) => { form.noValidate = true })
    await profile.getByRole('button', { name: 'Update', exact: true }).click()
    expect((await response).headers()['cache-control']).toBe('private, no-store')
    await expect(profile.getByText('Enter a valid email address.', { exact: true })).toBeVisible()
    await expect(profile.getByRole('textbox', { name: /^Name/ })).toHaveValue('Private person <draft>')
    expect(page.url()).not.toContain('Private')
    await expect(page.locator('html')).toHaveAttribute('data-color-mode', 'dark')
    page.once('dialog', dialog => dialog.accept())
    await profile.getByRole('link', { name: 'Cancel', exact: true }).click()
    await expect(profile).toBeHidden()
    await nav.getByRole('link', { name: 'Organizations', exact: true }).click()
    await page.getByRole('link', { name: 'Client Organization', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'General', exact: true, level: 1 })).toBeVisible()
    await expect(nav.getByRole('link', { name: 'Organizations', exact: true })).toHaveCount(0)
    await expect(nav.getByRole('button', { name: 'Change organization: Client Organization', exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Edit organization', exact: true }).click()
    const organization = page.getByRole('dialog', { name: 'Edit organization', exact: true })
    await expect(organization.getByRole('textbox', { name: /^Name/ })).toHaveValue('Client Organization')
    await organization.getByRole('textbox', { name: /^Name/ }).fill('Checked organization')
    await organization.getByRole('button', { name: 'Update', exact: true }).click()
    await expect(organization.getByText('Organization details checked', { exact: true })).toBeVisible()
    await expect(organization.getByRole('textbox', { name: /^Name/ })).toHaveValue('Client Organization')
    await organization.getByRole('link', { name: 'Cancel', exact: true }).click()
    await expect(organization).toBeHidden()
    await nav.getByRole('link', { name: 'Billing', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Billing', exact: true, level: 1 })).toBeVisible()
    await nav.getByRole('button', { name: 'Change organization: Client Organization', exact: true }).click()
    await page.getByRole('menuitem', { name: /^Example Household/ }).click()
    await expect(page.getByRole('heading', { name: 'Billing', exact: true, level: 1 })).toBeVisible()
    await expect(nav.getByRole('button', { name: 'Change organization: Example Household', exact: true })).toBeVisible()
    await nav.getByRole('link', { name: '← Ledger', exact: true }).click()
    await expect(page).toHaveURL(url => url.searchParams.get('organization') === 'example-household' && url.searchParams.get('ledger') === 'jordan' && url.searchParams.get('environment') === 'staging' && !url.searchParams.has('returnOrganization'))
    await expect(page.getByRole('button', { name: 'Open workspace menu: Jordan', exact: true })).toBeVisible()
    expect(errors).toEqual([])
  })
}
