import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('mobile record checkboxes align with field labels without shrinking click targets', async ({ page }) => {
  for (const width of [390, 640]) {
    await page.setViewportSize({ width, height: 1200 })
    for (const route of ['collection', 'detail']) {
      await page.goto(`/components/${route}`)
      const table = page.getByRole('table', { name: route === 'collection' ? 'Accounts' : 'Transactions', exact: true })
      const row = table.locator('tbody tr').first()
      await expect(row).toHaveCSS('display', 'grid')
      for (const size of ['', '200%']) {
        await page.evaluate(size => { document.documentElement.style.fontSize = size }, size)
        const checkbox = row.getByRole('checkbox')
        const all = table.getByRole('checkbox', { name: 'Select all rows on this page' })
        const label = row.locator('.fve-table-mobile-label').first()
        if (route === 'detail') {
          const status = row.locator('[data-mobile-cell="field"]').filter({ has: page.getByText('Status', { exact: true }) })
          await expect(status.getByText('Status', { exact: true })).toBeVisible()
          const badge = status.getByText('Verified', { exact: true })
          await expect(badge).toBeVisible()
          const badgeSize = await badge.evaluate(element => {
            const range = document.createRange()
            range.selectNodeContents(element)
            const style = getComputedStyle(element)
            return { width: element.getBoundingClientRect().width, content: range.getBoundingClientRect().width + parseFloat(style.paddingLeft) + parseFloat(style.paddingRight), lines: range.getClientRects().length }
          })
          expect(badgeSize.lines).toBe(1)
          expect(badgeSize.width).toBeCloseTo(badgeSize.content, 0)
          expect(badgeSize.width).toBeLessThan((await status.boundingBox())!.width)
          expect(Math.abs((await status.boundingBox())!.x - (await label.boundingBox())!.x)).toBeLessThanOrEqual(1)
        }
        const box = (await checkbox.boundingBox())!
        expect(Math.abs(box.x - (await label.boundingBox())!.x)).toBeLessThanOrEqual(1)
        expect(Math.abs(box.x - (await all.boundingBox())!.x)).toBeLessThanOrEqual(1)
        const target = row.locator('label')
        const targetBox = (await target.boundingBox())!
        expect(targetBox.width).toBeGreaterThanOrEqual(28)
        expect(targetBox.height).toBeGreaterThanOrEqual(28)
        const primaryBox = (await row.getByRole('rowheader').boundingBox())!
        expect(primaryBox.x).toBeGreaterThanOrEqual(targetBox.x + targetBox.width)
        await target.click({ position: { x: 1, y: 1 } })
        await expect(checkbox).toBeChecked()
        await checkbox.uncheck()
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      }
    }
  }
})

test('selectable tables recompose one accessible tree into mobile records', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/components/collection')
  const selection = page.locator('#accounts-selection')
  const table = selection.getByRole('table', { name: 'Accounts', exact: true })
  const all = table.getByRole('checkbox', { name: 'Select all rows on this page' })
  const assets = table.getByRole('checkbox', { name: 'Select Assets', exact: true })
  await expect(all).not.toBeChecked()
  await expect(table.getByRole('checkbox', { name: 'Select Placeholder' })).toBeDisabled()
  await assets.check()
  await expect(all).toBeChecked({ indeterminate: true })
  await expect(selection.getByRole('status').filter({ hasText: 'selected on this page' })).toHaveText('1 selected on this page')
  await all.check()
  await expect(table.locator('input:checked')).toHaveCount(6)
  await all.uncheck()
  await expect(table.locator('input:checked')).toHaveCount(0)
  await assets.focus()
  await assets.press('Space')
  await expect(assets).toBeChecked()
  const row = table.getByRole('row').filter({ has: page.getByRole('checkbox', { name: 'Select Assets', exact: true }) })
  expect((await row.boundingBox())!.height).toBeLessThanOrEqual(40)
  const trigger = row.getByRole('button', { name: 'More actions for Assets' })
  await expect(row.locator('[data-mobile-cell="actions"]')).toHaveCSS('border-left-width', '0px')
  const identity = await assets.elementHandle()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(row).toHaveCSS('display', 'grid')
  await expect(assets).toBeChecked()
  expect(await assets.evaluate((element, original) => element === original, identity)).toBe(true)
  await expect(table.getByRole('rowheader')).toHaveCount(6)
  await expect(row.getByText('Commodity', { exact: true })).toBeVisible()
  expect(await table.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await trigger.click()
  const menu = table.getByRole('menu', { name: 'More actions for Assets' })
  await expect(menu).toBeVisible()
  await expect(menu).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(menu.getByRole('menuitem', { name: 'View account' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await expect(assets).toBeChecked()
  const accessibility = await new AxeBuilder({ page }).include('#accounts-selection').analyze()
  expect(accessibility.violations).toEqual([])
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(assets).toBeVisible()
  await page.evaluate(() => { document.documentElement.style.fontSize = '' })
  await page.setViewportSize({ width: 1600, height: 1000 })
  await expect(row).toHaveCSS('display', 'table-row')
  await expect(assets).toBeChecked()
  await page.getByRole('button', { name: 'Choose color theme' }).click()
  await page.getByRole('menuitemradio', { name: 'Dark' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect((await new AxeBuilder({ page }).include('#accounts-selection').analyze()).violations).toEqual([])
  await page.emulateMedia({ forcedColors: 'active' })
  await all.focus()
  await page.keyboard.press('Tab')
  await expect(assets).toBeFocused()
  await expect(assets).toHaveCSS('outline-style', 'solid')
  await assets.press('Space')
  await expect(assets).not.toBeChecked()
  expect(errors).toEqual([])
})

test('table selection reports keys and survives a real fixture morph @cross-browser', async ({ page }) => {
  await page.goto('/components/page-examples/account-management?destination=ledger-accounts')
  const shell = page.locator('#ledger-app-shell')
  await page.evaluate(() => {
    (window as any).selectedKeys = []
    document.addEventListener('fve-table-selection-change', event => { (window as any).selectedKeys = (event as CustomEvent).detail.keys })
  })
  const selected = shell.getByRole('checkbox', { name: 'Select Assets', exact: true })
  await selected.check()
  await expect.poll(() => page.evaluate(() => (window as any).selectedKeys)).toEqual(['101'])
  await expect(selected).toHaveAttribute('name', 'accountIds')
  await expect(selected).toHaveAttribute('value', '101')
  const nativeValues = await shell.locator('[data-fve-table]').evaluate(element => {
    const form = document.createElement('form')
    const clone = element.cloneNode(true)
    form.append(clone)
    return new FormData(form).getAll('accountIds')
  })
  expect(nativeValues).toEqual(['101'])
  const accountsLink = shell.getByRole('navigation', { name: 'Ledger primary navigation' }).getByRole('link', { name: 'Accounts', exact: true })
  await expect(accountsLink).toHaveAttribute('aria-current', 'page')
  const [response] = await Promise.all([
    page.waitForResponse(response => response.url().includes('/components/page-examples/account-management/fixture?destination=ledger-accounts')),
    accountsLink.dispatchEvent('click'),
  ])
  expect(response.status()).toBe(200)
  await expect(selected).toBeChecked()
  await expect(shell.getByRole('checkbox', { name: 'Select all rows on this page' })).toBeChecked({ indeterminate: true })
})

test('canvas pages own scrolling and working zoom without constraining the workspace', async ({ page }) => {
  await page.goto('/components/page')
  const canvas = page.locator('[data-fve-page-canvas]')
  await expect(canvas).toBeVisible()
  const scroller = canvas.getByRole('region', { name: 'Posting flow canvas' })
  await expect(canvas).toHaveCSS('overflow', 'hidden')
  await expect(scroller).toHaveCSS('overflow', 'auto')
  await canvas.getByRole('button', { name: 'Zoom in' }).click()
  await expect(canvas.getByLabel('Zoom level')).toHaveText('125%')
  await canvas.getByRole('button', { name: 'Zoom out' }).click()
  await expect(canvas.getByLabel('Zoom level')).toHaveText('100%')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await scroller.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
})
