import { test, expect } from '@playwright/test'

test('catalog Preview Code and history retain the selected financial page', async ({ page }) => {
  await page.goto('/examples/application/accounts')
  await page.evaluate(() => (window as any).templateDocument = 'retained')
  await page.getByRole('navigation', { name: 'Example view' }).getByRole('link', { name: 'Code', exact: true }).click()
  await page.getByRole('navigation', { name: 'Template source files' }).getByRole('link', { name: 'Domain/Domain.fs', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Domain/Domain.fs', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: 'Example view' }).getByRole('link', { name: 'Preview', exact: true }).click()
  await expect(page.getByRole('navigation', { name: 'Breadcrumb', exact: true }).getByText('Accounts', { exact: true })).toBeVisible()
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Template source', exact: true })).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('link', { name: 'Operating checking', exact: true })).toBeVisible()
  expect(await page.evaluate(() => (window as any).templateDocument)).toBe('retained')
})

test('spec App mode follows an exact account through validation cancel and current-state exit @cross-browser', async ({ page }) => {
  await page.goto('/examples/specification/accounts/view-accounts')
  await page.getByRole('tab', { name: 'Assets', exact: true }).click()
  const assets = page.getByRole('tabpanel', { name: 'Assets', exact: true })
  await expect(assets.getByRole('link', { name: 'Operating checking', exact: true })).toBeVisible()
  await expect(assets.getByRole('link', { name: 'Unassigned expense', exact: true })).toHaveCount(0)
  await page.getByRole('tab', { name: 'Hierarchy', exact: true }).click()
  await page.getByRole('link', { name: 'Open View accounts · Hierarchy in App mode', exact: true }).click()
  await expect(page).toHaveURL(/appMode=1/)
  await expect(page.getByRole('navigation', { name: 'App mode controls' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Example view' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Unassigned expense', exact: true }).click()
  await expect(page).toHaveURL(/accounts\/view-account.*resource=105.*appMode=1/)
  await page.getByRole('link', { name: 'Edit account', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit Unassigned expense', exact: true })
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('navigation', { name: 'App mode controls' })).toBeVisible()
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('Tax reserve')
  await dialog.getByRole('button', { name: 'Save account', exact: true }).click()
  await expect(dialog.getByText('Check the account name and type', { exact: true })).toBeVisible()
  await dialog.getByRole('button', { name: 'Move App mode controls to top', exact: true }).click()
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('Unused expense label')
  await dialog.getByRole('button', { name: 'Save account', exact: true }).click()
  await expect(dialog.getByText('Account validated', { exact: true })).toBeVisible()
  await expect(page).toHaveURL(/fveAppDock=top/)
  await expect(dialog.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('Unassigned expense')
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/accounts\/view-account.*resource=105.*appMode=1.*fveAppDock=top/)
  await page.getByRole('link', { name: 'Delete account', exact: true }).click()
  const deletion = page.getByRole('dialog', { name: 'Delete Unassigned expense?', exact: true })
  await expect(deletion).toBeVisible()
  await expect(deletion.getByRole('link', { name: 'Exit App mode', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page).toHaveURL(/accounts\/view-account.*resource=105.*appMode=1.*fveAppDock=top/)
  await page.getByRole('link', { name: 'Exit App mode', exact: true }).click()
  await expect(page).toHaveURL(/accounts\/view-account.*resource=105/)
  expect(new URL(page.url()).searchParams.has('appMode')).toBe(false)
  await expect(page.getByRole('heading', { name: 'View account', exact: true, level: 1 })).toBeVisible()
})

test('workspace menu and appearance preferences survive App mode document navigation', async ({ page }) => {
  await page.goto('/examples/specification/home?appMode=1')
  const controls = page.getByRole('navigation', { name: 'App mode controls' })
  await controls.getByRole('button', { name: 'Move App mode controls to top', exact: true }).click()
  await controls.getByRole('button', { name: 'Choose theme', exact: true }).click()
  await page.getByRole('menuitemradio', { name: 'Dark', exact: true }).click()
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.getByRole('button', { name: 'Open workspace menu: Alex', exact: true }).click()
  await page.getByRole('menuitem', { name: 'Jordan', exact: true }).click()
  await expect(page).toHaveURL(/ledger=jordan.*appMode=1.*fveAppDock=top/)
  await expect(page.locator('html')).toHaveClass(/dark/)
  await page.getByRole('link', { name: 'Andrew Meier', exact: true }).click()
  await expect(page).toHaveURL(/specification\/profile.*ledger=jordan.*appMode=1/)
  const light = page.getByRole('radio', { name: 'Light', exact: true })
  await light.focus()
  await page.keyboard.press('Space')
  await expect(light).toBeChecked()
  await expect(page.locator('html')).not.toHaveClass(/dark/)
  await page.reload()
  await expect(page.locator('html')).not.toHaveClass(/dark/)
  await expect(page.getByRole('navigation', { name: 'App mode controls' })).toBeVisible()
})

test('rendered architecture nodes navigate from system context to project contracts', async ({ page }) => {
  await page.goto('/examples/specification/architecture')
  await page.getByRole('region', { name: 'Ledger system context', exact: true }).locator('svg a').click()
  await expect(page).toHaveURL(/architecture\/solution/)
  await page.getByRole('region', { name: 'Ledger project dependencies and HTTP boundary', exact: true }).locator('svg a').filter({ hasText: 'Ledger.Application' }).click()
  await expect(page).toHaveURL(/architecture\/solution\/application/)
  await expect(page.getByRole('heading', { name: 'Operations', exact: true })).toBeVisible()
  await expect(page.getByText(/UseCases\/Operations.fs owns|UseCases\/Operations.fs validates/)).toBeVisible()
})

test('API response tabs and copied cURL remain usable in a narrow layout', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.setViewportSize({ width: 320, height: 844 })
  await page.goto('/examples/api-documentation/create-account')
  await page.getByRole('tab', { name: '400', exact: true }).click()
  await expect(page.getByRole('tabpanel', { name: '400', exact: true })).toContainText('validation_failed')
  await page.getByRole('button', { name: /Copy.*code/ }).first().click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toContain('curl')
  const copied = await page.evaluate(() => navigator.clipboard.readText())
  expect(copied).toContain('$API_ORIGIN')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('shared shell and editor keep actions reachable at narrow enlarged text', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 900 })
  await page.goto('/examples/specification/accounts/update-account?appMode=1&resource=105')
  await page.locator('html').evaluate(el => el.style.fontSize = '200%')
  const dialog = page.getByRole('dialog', { name: 'Edit Unassigned expense', exact: true })
  await expect(dialog.getByRole('button', { name: 'Save account', exact: true })).toBeVisible()
  await expect(dialog.getByRole('link', { name: 'Exit App mode', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await dialog.getByRole('textbox', { name: 'Name', exact: true }).fill('Expense validation')
  await dialog.getByRole('button', { name: 'Save account', exact: true }).click()
  await expect(dialog.getByText('Account validated', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
