<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <PackageId>FSharp.ViewEngine</PackageId>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Authors>Andrew Meier</Authors>
    <RepositoryUrl>https://github.com/meiermade/FSharp.ViewEngine</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Core.fs" />
    <Compile Include="Html.fs" />
    <Compile Include="Htmx.fs" />
    <Compile Include="Alpine.fs" />
    <Compile Include="Tailwind.fs" />
    <Compile Include="Svg.fs" />
    <Compile Include="Datastar.fs" />
    <None Include="../../LICENSE" Pack="True" Visible="false" PackagePath="" />
    <None Include="../../README.md" Pack="True" Visible="false" PackagePath="" />
    <Content Include="paket.references" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
