<?xml version="1.0" encoding="utf-8"?>
<Project>
  <!-- Only independently installable components and their tightly coupled helpers are distributed. -->
  <ItemGroup>
    <FveComponent Include="$(MSBuildThisFileDirectory)Foundation.fs" FveFile="Foundation.fs" FveName="foundation" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Card.fs" FveFile="Card.fs" FveName="card" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Progress.fs" FveFile="Progress.fs" FveName="progress" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)FileSelection.fs" FveFile="FileSelection.fs" FveName="file-selection" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Browser.fs" FveFile="Browser.fs" FveName="browser" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Phone.fs" FveFile="Phone.fs" FveName="phone" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)CodeAssets.fs" FveFile="CodeAssets.fs" FveName="code-assets" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)CodeBlock.fs" FveFile="CodeBlock.fs" FveName="code-block" FveDependencies="code-assets" />
    <FveComponent Include="$(MSBuildThisFileDirectory)MermaidAssets.fs" FveFile="MermaidAssets.fs" FveName="mermaid-assets" FveDependencies="" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Mermaid.fs" FveFile="Mermaid.fs" FveName="mermaid" FveDependencies="mermaid-assets" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Kbd.fs" FveFile="Kbd.fs" FveName="kbd" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Separator.fs" FveFile="Separator.fs" FveName="separator" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Skeleton.fs" FveFile="Skeleton.fs" FveName="skeleton" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Item.fs" FveFile="Item.fs" FveName="item" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Button.fs" FveFile="Button.fs" FveName="button" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Badge.fs" FveFile="Badge.fs" FveName="badge" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)LoadingIndicator.fs" FveFile="LoadingIndicator.fs" FveName="loading-indicator" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)EmptyState.fs" FveFile="EmptyState.fs" FveName="empty-state" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Table.fs" FveFile="Table.fs" FveName="table" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)DescriptionList.fs" FveFile="DescriptionList.fs" FveName="description-list" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Metric.fs" FveFile="Metric.fs" FveName="metric" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Pagination.fs" FveFile="Pagination.fs" FveName="pagination" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ChoiceSelection.fs" FveFile="ChoiceSelection.fs" FveName="choice-selection" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)TagInput.fs" FveFile="TagInput.fs" FveName="tag-input" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Checkbox.fs" FveFile="Checkbox.fs" FveName="checkbox" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Switch.fs" FveFile="Switch.fs" FveName="switch" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ToggleButton.fs" FveFile="ToggleButton.fs" FveName="toggle-button" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Tabs.fs" FveFile="Tabs.fs" FveName="tabs" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)RadioGroup.fs" FveFile="RadioGroup.fs" FveName="radio-group" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)CalendarRendering.fs" FveFile="CalendarRendering.fs" FveName="calendar-rendering" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Resizable.fs" FveFile="Resizable.fs" FveName="resizable" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)BottomNavigation.fs" FveFile="BottomNavigation.fs" FveName="bottom-navigation" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Steps.fs" FveFile="Steps.fs" FveName="steps" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)FieldFoundation.fs" FveFile="FieldFoundation.fs" FveName="field-foundation" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Avatar.fs" FveFile="Avatar.fs" FveName="avatar" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)PageTopBar.fs" FveFile="PageTopBar.fs" FveName="page-top-bar" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)PageHeader.fs" FveFile="PageHeader.fs" FveName="page-header" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)SectionHeader.fs" FveFile="SectionHeader.fs" FveName="section-header" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)FSharpApiReference.fs" FveFile="FSharpApiReference.fs" FveName="fsharp-api-reference" FveDependencies="code-block" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Callout.fs" FveFile="Callout.fs" FveName="callout" FveDependencies="foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Example.fs" FveFile="Example.fs" FveName="example" FveDependencies="code-block" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ChoiceCards.fs" FveFile="ChoiceCards.fs" FveName="choice-cards" FveDependencies="foundation;choice-selection" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Notice.fs" FveFile="Notice.fs" FveName="notice" FveDependencies="foundation;field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Notification.fs" FveFile="Notification.fs" FveName="notification" FveDependencies="foundation;field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ToggleGroup.fs" FveFile="ToggleGroup.fs" FveName="toggle-group" FveDependencies="foundation;choice-selection" />
    <FveComponent Include="$(MSBuildThisFileDirectory)DropdownMenu.fs" FveFile="DropdownMenu.fs" FveName="dropdown-menu" FveDependencies="foundation;button" />
    <FveComponent Include="$(MSBuildThisFileDirectory)SideNav.fs" FveFile="SideNav.fs" FveName="side-nav" FveDependencies="foundation;dropdown-menu" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ThemeSwitcher.fs" FveFile="ThemeSwitcher.fs" FveName="theme-switcher" FveDependencies="dropdown-menu" />
    <FveComponent Include="$(MSBuildThisFileDirectory)FloatingPanel.fs" FveFile="FloatingPanel.fs" FveName="floating-panel" FveDependencies="foundation;field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Tooltip.fs" FveFile="Tooltip.fs" FveName="tooltip" FveDependencies="foundation;field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Popover.fs" FveFile="Popover.fs" FveName="popover" FveDependencies="foundation;field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)DayCalendar.fs" FveFile="DayCalendar.fs" FveName="day-calendar" FveDependencies="calendar-rendering" />
    <FveComponent Include="$(MSBuildThisFileDirectory)WeekCalendar.fs" FveFile="WeekCalendar.fs" FveName="week-calendar" FveDependencies="calendar-rendering" />
    <FveComponent Include="$(MSBuildThisFileDirectory)MonthCalendar.fs" FveFile="MonthCalendar.fs" FveName="month-calendar" FveDependencies="calendar-rendering;field-foundation;popover" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Message.fs" FveFile="Message.fs" FveName="message" FveDependencies="foundation;field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Input.fs" FveFile="Input.fs" FveName="input" FveDependencies="field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Textarea.fs" FveFile="Textarea.fs" FveName="textarea" FveDependencies="field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ErrorSummary.fs" FveFile="ErrorSummary.fs" FveName="error-summary" FveDependencies="field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)CopyReveal.fs" FveFile="CopyReveal.fs" FveName="copy-reveal" FveDependencies="foundation;button" />
    <FveComponent Include="$(MSBuildThisFileDirectory)NativeOverlay.fs" FveFile="NativeOverlay.fs" FveName="native-overlay" FveDependencies="foundation;button" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Field.fs" FveFile="Field.fs" FveName="field" FveDependencies="field-foundation" />
    <FveComponent Include="$(MSBuildThisFileDirectory)InputGroup.fs" FveFile="InputGroup.fs" FveName="input-group" FveDependencies="foundation;kbd;field-foundation;field;input" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Select.fs" FveFile="Select.fs" FveName="select" FveDependencies="foundation;choice-selection;field-foundation;input" />
    <FveComponent Include="$(MSBuildThisFileDirectory)ButtonGroup.fs" FveFile="ButtonGroup.fs" FveName="button-group" FveDependencies="foundation;button;dropdown-menu;select" />
    <FveComponent Include="$(MSBuildThisFileDirectory)YearCalendar.fs" FveFile="YearCalendar.fs" FveName="year-calendar" FveDependencies="month-calendar" />
    <FveComponent Include="$(MSBuildThisFileDirectory)DatePicker.fs" FveFile="DatePicker.fs" FveName="date-picker" FveDependencies="foundation;field-foundation;popover;month-calendar" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Breadcrumbs.fs" FveFile="Breadcrumbs.fs" FveName="breadcrumbs" FveDependencies="foundation;dropdown-menu" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Dialog.fs" FveFile="Dialog.fs" FveName="dialog" FveDependencies="native-overlay" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Drawer.fs" FveFile="Drawer.fs" FveName="drawer" FveDependencies="native-overlay" />
    <FveComponent Include="$(MSBuildThisFileDirectory)FieldGroup.fs" FveFile="FieldGroup.fs" FveName="field-group" FveDependencies="field" />
    <FveComponent Include="$(MSBuildThisFileDirectory)Command.fs" FveFile="Command.fs" FveName="command" FveDependencies="foundation;dialog" />
    <Compile Include="@(FveComponent)" Condition="'$(FveCompileRegistry)' != 'false'" />
  </ItemGroup>
</Project>
