<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>$(NoWarn);NU1510</NoWarn>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="paket.references" />
    <Compile Include="src\Common\Config.fs" />
    <Compile Include="src\Common\Model.fs" />
    <Compile Include="src\Common\View.fs" />
    <Compile Include="src\Pages\Home.fs" />
    <Compile Include="src\Pages\Installation.fs" />
    <Compile Include="src\Pages\Custom.fs" />
    <Compile Include="src\Pages\Usage.fs" />
    <Compile Include="src\Pages\Alpine.fs" />
    <Compile Include="src\Pages\Datastar.fs" />
    <Compile Include="src\Pages\Htmx.fs" />
    <Compile Include="src\Pages\Svg.fs" />
    <Compile Include="src\Pages\TailwindElements.fs" />
    <Compile Include="src\Pages\Benchmarks.fs" />
    <Compile Include="src\Pages\Changelog.fs" />
    <Compile Include="src\Pages\Registry.fs" />
    <Compile Include="src\Common\Handler.fs" />
    <Compile Include="src\Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="input.css">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FSharp.ViewEngine\FSharp.ViewEngine.fsproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
