<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="CoreTests.fs" />
    <Compile Include="DatastarTests.fs" />
    <Compile Include="HtmxTests.fs" />
    <Compile Include="AlpineTests.fs" />
    <Compile Include="SvgTests.fs" />
    <Compile Include="TailwindTests.fs" />
    <Compile Include="Program.fs" />
    <Content Include="paket.references" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FSharp.ViewEngine\FSharp.ViewEngine.fsproj" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
