name: Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Install Tools
        run: dotnet tool restore
        working-directory: ./fsharp-view-engine
      - name: Install Packages
        run: dotnet paket install
        working-directory: ./fsharp-view-engine
      - name: Test
        run: ./fake.sh Test
        working-directory: ./fsharp-view-engine
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    needs:
      - test
    steps:
      - uses: actions/checkout@v5
      - name: Authenticate Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: meiermade
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:meiermade
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Install Packages
        run: npm install
        working-directory: ./pulumi
      - name: Update
        uses: pulumi/actions@v6
        with:
          work-dir: ./pulumi
          command: up
          stack-name: prod
