name: Preview
on:
  pull_request:
    paths-ignore:
      - '**/*.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Install Tools
        run: dotnet tool restore
        working-directory: ./sln
      - name: Install Packages
        run: dotnet paket install
        working-directory: ./sln
      - name: Test
        run: ./fake.sh Test
        working-directory: ./sln
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 24
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: gke-gcloud-auth-plugin
      - name: Install Packages
        run: npm install
        working-directory: ./pulumi
      - name: Authenticate Pulumi
        uses: pulumi/auth-actions@v1
        with:
          organization: meiermade
          requested-token-type: urn:pulumi:token-type:access_token:personal
          scope: user:meiermade
      - name: Preview
        uses: pulumi/actions@v6
        with:
          work-dir: ./pulumi
          command: preview
          stack-name: prod
          diff: true
          comment-on-pr: true
