name: Publish
on:
  release:
    branches:
      - main
    types:
      - published
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Restore Tools
        run: dotnet tool restore
        working-directory: ./src
      - name: Install Packages
        run: dotnet paket install
        working-directory: ./src
      - name: Publish
        run: ./fake.sh PushNugets
        working-directory: ./src
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
